#!/usr/bin/env node

( function () {
    "use strict";

    const DEBUG = ( s ) => {
        console.log( s );
    };

    const NortonGuide = require( "./jsNG.js" );

    const ng = new NortonGuide( "/Users/davep/Google Drive/Norton Guides/cars.ng" );

    ng.open()

    if ( ng.isNG() ) {

        DEBUG( "Reading " + ng.filename() );
        DEBUG( "That looks like a Norton Guide" );
        DEBUG( "It was likely built with " + ng.type() );
        DEBUG( "Menu count: " + ng.menuCount() );
        DEBUG( "Title: " + ng.title() );
        DEBUG( "Credits: " + ng.credits() );

        DEBUG( "Menus: " );
        for ( let i = 0; i < ng.menuCount(); i++ ) {
            DEBUG( ng.menu( i ).title() );
        }
    } else {
        DEBUG( "I don't think that's a Norton Guide" );
    }

}() );

