#!/usr/bin/env node

( function () {
    "use strict";

    const DEBUG = ( s ) => {
        console.log( s );
    };

    const NortonGuide = require( "./jsNG.js" );

    const ng = new NortonGuide( "/Users/davep/Google Drive/Norton Guides/cars.ng" );

    ng.open()

    if ( ng.isNG() ) {

        DEBUG( "Reading " + ng.filename() );
        DEBUG( "That looks like a Norton Guide" );
        DEBUG( "It was likely built with " + ng.type() );
        DEBUG( "Title: " + ng.title() );
        DEBUG( "Credits: " + ng.credits() );

        for ( let i = 0; i < ng.menuCount(); i++ ) {

            DEBUG( "> " + ng.menu( i ).title() );

            for ( let j = 0; j < ng.menu( i ).promptCount(); j++ ) {
                DEBUG( "> > " + ng.menu( i ).prompt( j ) +
                     " (" + ng.menu( i ).offset( j ) + ")");
            }
        }

        // Ensure we're on the first entry.
        ng.goFirst();

        while ( !ng.eof() ) {
            const entry = ng.loadEntry();
            entry.lines().forEach( DEBUG );
            ng.nextEntry();
        }

    } else {
        DEBUG( "I don't think that's a Norton Guide" );
    }

}() );

