#!/usr/bin/env node

( ( args ) => {
    "use strict";

    const NG = require( "./jsNG" );

    for ( let file of args ) {

        const ng = new NG( file ).open();

        if ( ng.isNG() ) {
            console.log( file + "\n\t" + ng.title() );
        }

    }

} )( process.argv.slice( 2 ) );
