#!/usr/bin/env node

( ( args ) => {
    "use strict";

    const NG = require( "./jsNG" );

    let dir = ( a ) => {

        const file = a.next();

        if ( !file.done ) {
            ( new NG( file.value ) ).open( ( ng, error ) => {

                if ( error ) {
                    console.log( error );
                } else {
                    if ( ng.isNG() ) {
                        console.log( file.value + "\n\t" + ng.title() );
                    }
                }

                dir( a );

            } );
        }

    };

    dir( args[ Symbol.iterator ]() );

} )( process.argv.slice( 2 ) );
